"""empty message

Revision ID: 83916c2a4855
Revises: a8610dfe2afa
Create Date: 2021-11-03 16:35:49.357342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83916c2a4855'
down_revision = 'a8610dfe2afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('existe')
    op.create_unique_constraint(None, 'intentos', ['username_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intentos', type_='unique')
    op.create_table('existe',
    sa.Column('count', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
