"""empty message

Revision ID: a8610dfe2afa
Revises: aac4145879b4
Create Date: 2021-11-03 15:08:53.759296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8610dfe2afa'
down_revision = 'aac4145879b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrasGuardadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['username_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_id', sa.Integer(), nullable=True),
    sa.Column('intentos_act', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('cant_intentos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'cant_intentos')
    op.drop_table('intentos')
    op.drop_table('contrasGuardadas')
    # ### end Alembic commands ###
